// console.log("Hi everyone!!!!");
var x = 10;
// x = 2564;
var y = 123;
console.log(x + y);
// var num: number = 50;
// var grer: string = "games";
// var fels: boolean = true;
// var lies: boolean = false;
// var undefi: undefined = undefined;
// var gery: null = null;
// var kilt: string | number = 50;
// var jif: string[] = ["Ambush", "Lovish", "kimish"];
// var khg: [boolean, number] = [true, 22];
// var posf = 40 + 5 + "5";
// console.log(num);
// console.log(grer);
// console.log(fels);
// console.log(lies);
// console.log(undefi);
// console.log(gery);
// console.log(kilt);
// console.log("Your name is " + jif[1]);
// console.log(khg[1]);
// console.log(posf);
